In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = sns.load_dataset("iris")

In [3]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
features = data.drop("species", axis=1)
labels = data["species"]

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings("ignore",category=FutureWarning)
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(features, labels, test_size=0.2, random_state=42)

In [7]:
model = RandomForestClassifier()
params ={
    "n_estimators":[10,20,30,50,100],
    "max_depth":[10,20,30,50,None]
}

cv = GridSearchCV(model, params, cv= 5)
cv.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [10, 20, 30, 50, None],
                         'n_estimators': [10, 20, 30, 50, 100]})

In [9]:
def print_results(cv):
    print("the best parameters are {}".format(cv.best_params_))
    
    mean = cv.cv_results_["mean_test_score"]
    
    for mn, parms in zip(mean, cv.cv_results_["params"]):
        print("the mean for params {} is {}".format(parms, mn))

In [10]:
print_results(cv)

the best parameters are {'max_depth': 10, 'n_estimators': 20}
the mean for params {'max_depth': 10, 'n_estimators': 10} is 0.9416666666666668
the mean for params {'max_depth': 10, 'n_estimators': 20} is 0.95
the mean for params {'max_depth': 10, 'n_estimators': 30} is 0.9416666666666667
the mean for params {'max_depth': 10, 'n_estimators': 50} is 0.95
the mean for params {'max_depth': 10, 'n_estimators': 100} is 0.95
the mean for params {'max_depth': 20, 'n_estimators': 10} is 0.9416666666666667
the mean for params {'max_depth': 20, 'n_estimators': 20} is 0.9416666666666668
the mean for params {'max_depth': 20, 'n_estimators': 30} is 0.9416666666666667
the mean for params {'max_depth': 20, 'n_estimators': 50} is 0.9416666666666667
the mean for params {'max_depth': 20, 'n_estimators': 100} is 0.95
the mean for params {'max_depth': 30, 'n_estimators': 10} is 0.9333333333333333
the mean for params {'max_depth': 30, 'n_estimators': 20} is 0.9333333333333333
the mean for params {'max_depth'

In [23]:
### model is 

model = RandomForestClassifier(n_estimators=20, max_depth=10)
model = model.fit(X_train, Y_train)
Y_pred = model.predict(X_test)


In [24]:
accuracy_score(Y_test, Y_pred)

1.0

In [12]:
Y_pred = cv.predict(X_test)

In [18]:
from sklearn.metrics import precision_recall_fscore_support

In [22]:
precision_recall_fscore_support(Y_test, Y_pred)

(array([1., 1., 1.]),
 array([1., 1., 1.]),
 array([1., 1., 1.]),
 array([10,  9, 11], dtype=int64))

In [25]:
model.feature_importances_

array([0.04191062, 0.02410929, 0.48650688, 0.44747321])